language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "current"

before_install:
  - npm install -g npm

install:
  - npm install

script:
  - npm audit
  - npm run lint
  - npm run test
