language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "default"
  - "node"
  - "current"
  - "stable"

before_install:
  - npm install -g npm

install:
  - npm install

script:
  - npm audit
  - npm run lint
  - npm run test
